### ISSUE TITLE
Python script error

### ISSUE THREAD

**Issue by kenneth-Q** [kicad-spice-library/KiCad-Spice-Library#1]
Thanks for this project, I think it could be better.
I got an error like:
>[Ken@kenpc Scripts]$ python check_supported.py
>Write 'exit' when you want to stop
>Write here the part you are looking for: 555
>555 not found, maybe you meant one of these: 555_pwr, atod_555, atod_555_nx, bb555/sie, bb555_in, bcr555/sie, bcr555_in, cd4555b, din555, do555, do555_nx, dtoa_555, fmmt555, fmmt555_zx, fxt555, fxt555_zx, io_555, irf7555_ir, j555, lm555, pmbt5550, pmbt5551, pmst5550, pmst5551, q2n5550, q2n5551, s0555r, tlc555_ti, ts555h, ts555h_st, ts555l, ts555l_st, ts555m, ts555m_st, ua555, ztx555, ztx555_zx
>Would you like to do another search? lm555
>Traceback (most recent call last):
>  File "check_supported.py", line 68, in <module>
>    search(to_search)
>  File "check_supported.py", line 38, in search
>    print_match(module)
>  File "check_supported.py", line 16, in print_match
>    path = ', '.join(p[p.index(folder_name)+len(folder_name):] for p in supported[part])
>  File "check_supported.py", line 16, in <genexpr>
>    path = ', '.join(p[p.index(folder_name)+len(folder_name):] for p in supported[part])
>ValueError: substring not found

OS: manjaro xfce 64bit

>[Ken@kenpc Scripts]$ python -V
>Python 3.7.3

**Comment by kenneth-Q** [comment]
After reinstall operating system, problem was solved.
